# Generated by Django 5.2 on 2025-05-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Qisqacha tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='product_category_image/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='product_images')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taste', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=30, verbose_name="Asl narx (so'm)")),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name="Chegirma narxi (so'm)")),
                ('discount_percent', models.PositiveIntegerField(blank=True, null=True, verbose_name='Chegirma foizi (%)')),
                ('prepayment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Agar oldindan to‘lov talab qilinsa, shu yerga summani kiriting', max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Ombordagi soni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol holatda')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
