# Generated by Django 5.2 on 2025-06-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Asl narx (so'm)"),
        ),
    ]
