# Generated by Django 5.2 on 2025-05-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='color_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='color_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producttaste',
            name='taste',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producttaste',
            name='taste_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producttaste',
            name='taste_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='discount_price',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Chegirma narxi (so'm)"),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.CharField(max_length=30, verbose_name="Asl narx (so'm)"),
        ),
        migrations.AlterField(
            model_name='productvolume',
            name='volume',
            field=models.CharField(max_length=100),
        ),
    ]
