# Generated by Django 5.2 on 2025-05-21 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productcolor_color_alter_productcolor_color_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='prepayment_amount',
        ),
        migrations.AddField(
            model_name='product',
            name='prepayment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Agar oldindan to‘lov talab qilinsa, shu yerga summani kiriting', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productcolor'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productsize'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='taste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.producttaste'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productvolume'),
        ),
    ]
