# Generated by Django 5.2 on 2025-06-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productvariant_price'),
        ('shop', '0004_shop_humo_card_shop_uz_card_shop_visa_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('name', 'shop')},
        ),
    ]
