# Generated by Django 5.2 on 2025-06-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prepayment_amount',
            field=models.BigIntegerField(blank=True, help_text='Agar oldindan to‘lov talab qilinsa, shu yerga summani kiriting', null=True),
        ),
    ]
