# Generated by Django 5.2 on 2025-06-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='humo_card_holder',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Humo egasi'),
        ),
        migrations.AddField(
            model_name='shop',
            name='uz_card_holder',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Uzcard egasi'),
        ),
        migrations.AddField(
            model_name='shop',
            name='visa_card_holder',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Visa egasi'),
        ),
    ]
