# Generated by Django 5.2 on 2025-05-16 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productcolor_color_alter_productcolor_color_ru_and_more'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='product',
        ),
        migrations.AddField(
            model_name='basket',
            name='product_variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.productvariant'),
            preserve_default=False,
        ),
    ]
