# Generated by Django 5.2 on 2025-06-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_humo_card_holder_shop_uz_card_holder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='humo_card_holder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='uz_card_holder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='visa_card_holder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
