# Generated by Django 5.2 on 2025-06-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shop_humo_card_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='humo_card',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='uz_card',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='visa_card',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
