# Generated by Django 5.2 on 2025-05-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botuser', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='label',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='longitude',
        ),
    ]
