# Generated by Django 5.2 on 2025-05-16 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botuser', '0002_initial'),
        ('product', '0003_alter_productcolor_color_alter_productcolor_color_ru_and_more'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReklamaAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='reklama_admins/')),
                ('link', models.CharField(max_length=303)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productvariant'),
        ),
        migrations.CreateModel(
            name='ReklamaBotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='reklama_admins/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reklama', to='product.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reklama', to='shop.shop')),
            ],
        ),
    ]
