# Generated by Django 5.2 on 2025-06-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botuser', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
