# Generated by Django 5.2 on 2025-06-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botuser', '0003_order_address_alter_order_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionmethod',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='receptionmethod',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
