# Generated by Django 5.2 on 2025-05-20 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botuser', '0003_reklamaadmin_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteproduct',
            name='shop',
        ),
    ]
