# Generated by Django 5.2 on 2025-06-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botuser', '0004_receptionmethod_name_ru_receptionmethod_name_uz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.BigIntegerField(default=0),
        ),
    ]
