name: Build, Push to Docker Hub & Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: | 
        echo "${{ secrets.DOTENV }}" > .env
        docker build -t ${{ secrets.DOCKER_USERNAME }}/market-back .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/market-back

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts

    - name: SSH to server and pull & run image
      run: |
        ssh ${{ secrets.USER }}@${{ secrets.IP }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/market-back
          docker stop market-back || true
          docker rm market-back || true
          docker run -d --name market-back -p 8001:8000 ${{ secrets.DOCKER_USERNAME }}/market-back
          docker image prune -f
        EOF
